2 make camodocal its own package that can be installed
TanPinDa/VINS-Mono pull request #7
Opened 2024-05-24 13:45 UTC by TanPinDa

Rename camera_model to camodocal. Make the package a static library and total not ROS related

2024-05-24 13:46 UTC, TanPinDa commented
Need to wait for  https://github.com/TanPinDa/VINS-Mono/pull/4

2024-05-25 12:57 UTC, KeeJin requested changes

2024-05-25 12:57 UTC, KeeJin commented on camodocal/package.xml
Since it is now a cpp library, maybe no need for package.xml anymore

2024-05-25 13:24 UTC, KeeJin approved these changes

2024-05-25 13:24 UTC, merged